### ISSUE TITLE
Some problems in predicting new network images

### ISSUE THREAD

**Issue by YangPeppa** [ShivamDuggal4/TARS3D#3]
Hi Shivam: 
	I have some questions to test on the new image. If I need to recreate a network image of a new chair, do I need other inputs besides that image?
	In addition, I also saw a problem with camera perspective from another issue. For a new image, do we need a camera parameter as an input in order to convert 3 D coordinates? If so, is it possible to use another network to predict this part of the camera parameters (I think it is possible to fix the world coordinates and camera parameters, just predict the rotation matrix and the offset matrix)?
	Or did you write this part of the code to predict new network images?
	Many thanks in advance.

Best,
Yang

**Comment by ShivamDuggal4** [comment]
Hi @YangPeppa 

During test time, we do not require the camera pose as input. The input to the pipeline is just a segmented image (image + segmentation mask) of the object.
Camera poses are only required during training to supervise the 3D reconstruction and deformation modules via differentiable rendering. It is also possible to remove the requirement of camera poses during training (by jointly predicting the camera poses as you mentioned), but we do not explore that as part of this repository.


Best Regards
Shivam
