### ISSUE TITLE
How to get all evaluation metrices?

### ISSUE THREAD

**Issue by Wi-sc** [ShivamDuggal4/TARS3D#4]
Hi @ShivamDuggal4 

Thanks for your existing work. I just tried to play your model but didn't find out how to get the correct cd and f-score. (e.g. the distance or squared distance, the distance times 10 or not, point number).

Here is my implementation:
```
d1, d2, _, _= distChamfer(gt_pc, pred_pc)
d1 = d1.sqrt()
d2 = d2.sqrt()
precision = (d1<0.1).sum()/d1.shape[0]
recall = (d2<0.1).sum()/d2.shape[0]
```
Could you please check this or release your test script?

Thanks a lot!

**Comment by ShivamDuggal4** [comment]
HI @Wi-sc 

Thanks for your interest in our work!

The chamfer distance implementation is defined here: https://github.com/ShivamDuggal4/TARS3D/blob/6988d4e24442f8e0891166ba3516cdb2d7ee1582/misc/eval_3D.py#L114

The mathematical definitions of precision, recall metrics are defined in our supplementary section A.4.
Your precision, recall definitions look correct.

F-score is defined as the harmonic mean of precision and recall i.e. `2 * Precision * Recall / (Precision + Recall)`

The EMD implementation is adopted from: https://github.com/daerduoCarey/PyTorchEMD

Hope this helps!

Best Regards,
Shivam

**Comment by Wi-sc** [comment]
Hi @ShivamDuggal4,

Thanks for your reply. I still have questions about evaluation. 

1. How many points have you used for CD, EMD, F-score evaluation?
2. Did you scale the distance by 10?

I would appreciate it if you could help me to check it. Thanks a lot!

Best,
Wisc

**Comment by ShivamDuggal4** [comment]
Hi @Wi-sc 

Please find the answers to your questions below:
1. The point clouds for the metrics are sampled here: https://github.com/ShivamDuggal4/TARS3D/blob/6988d4e24442f8e0891166ba3516cdb2d7ee1582/misc/eval_3D.py#L105 and number of sampled point clouds equals the `num_points` parameter of the config: https://github.com/ShivamDuggal4/TARS3D/blob/6988d4e24442f8e0891166ba3516cdb2d7ee1582/configs/shapenet/base.yaml#L37 
2. Yes, the metrics are scaled by 10.

Best Regards,
Shivam

**Comment by dongjinkun** [comment]
Hi@Wi-sc 

I have encountered the same problem. (i.e. fscore) Unfortunately, I have tried to solve the problem by different methods, but still haven't resolved it.

So, I would like to ask you about the code implementation of fscore.

Thanks.
Best wishes,
dongjinkun
