### ISSUE TITLE
Train on other dataset

### ISSUE THREAD

**Issue by yichuan1998** [ShivamDuggal4/TARS3D#5]
Thanks for your great job. Could tars3d train on other dataset? like dog something?

**Comment by ShivamDuggal4** [comment]
Hi @yichuan1998 

Yes, the approach can work on any single-view image collections as long as you have segmentation masks, RGB images and camera poses for each object image.

You can refer to this issue: https://github.com/ShivamDuggal4/TARS3D/issues/2 to get some tips on how to setup your dataloader for the new dataset.

Thanks & Best Regards,
Shivam

**Comment by yichuan1998** [comment]
Thanks for your immediate reply, that issue really helps. Again, thanks very much.

**Comment by yichuan1998** [comment]
> Hi @yichuan1998
> 
> Yes, the approach can work on any single-view image collections as long as you have segmentation masks, RGB images and camera poses for each object image.
> 
> You can refer to this issue: #2 to get some tips on how to setup your dataloader for the new dataset.
> 
> Thanks & Best Regards, Shivam

Thanks for your immediate reply, that issue really helps. Again, thanks very much.
