### ISSUE TITLE
Where is the implementation of precision, recall and F-score?

### ISSUE THREAD

**Issue by dongjinkun** [ShivamDuggal4/TARS3D#6]
Hi, thank you for your excellent and interesting work, but I can't find the code that implements precision, recall and F-score.
So, can you tell me where the implementation code is?
thanks.

**Comment by dongjinkun** [comment]
@ShivamDuggal4

**Comment by dongjinkun** [comment]
@ShivamDuggal4

**Comment by ShivamDuggal4** [comment]
Hi @dongjinkun 

Thank you for the warm words!
Please check this answer for more details about the precision, recall and f-score metrics. https://github.com/ShivamDuggal4/TARS3D/issues/4#issuecomment-1382724752

Please let me know if the query still exists.

Best Regards,
Shivam

**Comment by dongjinkun** [comment]
Hi @ShivamDuggal4 
Thank you for your answer. But I still have some questions.
1. I can't find the code implementation of Precision, recall and f-score in TARS3D repository.
2. Can you tell me the specific location of code implementation of Precision, recall and f-score? For instance, https://github.com/ShivamDuggal4/TARS3D/blob/6988d4e24442f8e0891166ba3516cdb2d7ee1582/misc/eval_3D.py#L114

**Comment by dongjinkun** [comment]
@ShivamDuggal4 
Thank you for your answer. But I still have some questions.

I can't find the code implementation of Precision, recall and f-score in TARS3D repository.
Can you tell me the specific location of code implementation of Precision, recall and f-score? For instance,
[TARS3D/misc/eval_3D.py](https://github.com/ShivamDuggal4/TARS3D/blob/6988d4e24442f8e0891166ba3516cdb2d7ee1582/misc/eval_3D.py#L114)

Line 114 in [6988d4e](https://github.com/ShivamDuggal4/TARS3D/commit/6988d4e24442f8e0891166ba3516cdb2d7ee1582)

 def chamfer_distance(opt, X1, X2):

I would appreciate it if you could help me to check it. Thanks a lot!
Best Regards,
dongjinkun

**Comment by dongjinkun** [comment]
@ShivamDuggal4

Thank you for your answer. But I still have some questions.

1. I can't find the code implementation of Precision, recall and f-score in TARS3D repository.
2. Can you tell me the specific location of code implementation of Precision, recall and f-score? 
For instance, https://github.com/ShivamDuggal4/TARS3D/blob/6988d4e24442f8e0891166ba3516cdb2d7ee1582/misc/eval_3D.py#L114


I would appreciate it if you could help me to check it. Thanks a lot!
Best Regards,
dongjinkun

**Comment by ShivamDuggal4** [comment]
Hi @dongjinkun 

Unfortunately, the repository doesn't include the code for computing precision, recall, f-score matrices. 
But I think their mathematical formulae are simple enough to implement. Please let me know if you face any issue in implementing them.

Best Regards,
Shivam

**Comment by dongjinkun** [comment]
Hi @ShivamDuggal4 

Thank you again for your reply and excellent work.

Best wishes,
dongjinkun
